### ISSUE TITLE
neumes with no components

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#727] opened 2021-11-16 00:56 UTC
on occasion an otherwise valid MEI file will turn out to have a neume which is not associated with any neume components, and which is thus invisible on the facsimile.
![image](https://user-images.githubusercontent.com/67451875/141875605-a81d9797-738f-48ab-85d8-f570057a09fd.png)

these "invisible" neumes behave like other neumes in some ways, and affect the colour order (which appears to skip the component-less neume.) When the neumes within a syllable are re-grouped, the "invisible" neume moves to the front, changing the colour order of the neumes in the syllable.  
Since these empty neumes are invisible, they are also impossible for the user to delete, and should probably be prevented from existing.

**Comment by yinanazhou** [comment] 2022-03-07 23:41
Hi @annamorphism , I've tested the changes using a file, in which I deliberately delete all the ncs in a neume, and Neon can successfully detect and delete the empty neume. The colour order is also correct. 

However, I'm not so sure about why an empty neume will be generated, maybe a side product of several group/ungroup actions.

**Comment by JoyfulGen** [comment] 2022-03-31 14:00
It's back! So this has happened three times this week, but I'm quite sure it's generated by my actions on the file, rather than the OMR. The neume without nc's (let's call it nwnc for short) isn't in the straight-outta-OMR file and also if I reupload the modified file with the nwnc @yinanazhou's fix deletes it. I'm now trying to find the series of actions that causes the nwnc. Stay tuned.

**Comment by JoyfulGen** [comment] 2022-04-13 12:45
I've just realized that https://github.com/DDMAL/MEI_encoding/issues/29 is a duplicate of this. It has a whole bunch more example files of this same issue, if anyone needs them.

**Comment by JoyfulGen** [comment] 2022-04-20 12:58
I think I have something!! It looks like the nwnc issue is related to this one: https://github.com/DDMAL/Neon/issues/642. In that issue, @annamorphism discovered that if you group two neume components in an already fully grouped neume, it creates another neume within that same syllable, but that neume has no components. We didn't think it was a problem, because other than the colour order skipping one colour, nothing really happens. HOWEVER, if you then ungroup that syllable, Neon doesn't know what to do with that neume without components so it makes it into a separate syllable and gives it the offset values, which is what messes up the order! 

As an illustration, here are two nwnc hiding in a syllable (I grouped neume components within it twice, so it produced two nwnc). The only visible effect of this in Neon is that there are two colours missing in the neume colour order.

<img width="864" alt="254v nwnc within syllable (hiding)" src="https://user-images.githubusercontent.com/83373378/164234664-e5271cf6-9f0e-46ad-94a2-2d66c2e2027e.png">

And here are those same nwnc after I ungrouped that one syllable. They got the offset values for their bbox, so they went to the end of the staff, after the custos, but before the staff break.

<img width="741" alt="254v nwnc brought to light (sort of)" src="https://user-images.githubusercontent.com/83373378/164234670-a80ee7d1-ee15-40b4-8dc2-52d9b19506e0.png">

I think the solution then is to fix https://github.com/DDMAL/Neon/issues/642, because that's what's creating the nwnc in the first place. @annamorphism, would you agree that the best thing would be to make it so that if you group neume components within a grouped neume, nothing happens?

**Comment by annamorphism** [comment] 2022-04-20 18:08
Great sleuthing, @JoyfulGen! Yes, I agree the best solution is probably to make it so nothing happens when grouping neumes that are already grouped.

**Comment by yinanazhou** [comment] 2022-04-21 19:55
Hi @annamorphism and @JoyfulGen, I've pushed the changes.

**Comment by JoyfulGen** [comment] 2022-04-25 12:48
It works, thank you! Closing the issue now.

**Closed by JoyfulGen** 2022-04-25 12:48 UTC
