### ISSUE TITLE
Staff order wrong, very difficult to correct

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#714] opened 2021-09-14 15:19 UTC
**EDIT: Please refer to my December 15th comment for a summary of the situation and a possible solution!**

(This issue seems to be related to @annamorphism's comment of July 13th in this issue: https://github.com/DDMAL/Neon/issues/680)

In Einsiedeln folio 002r (the first Einsiedeln folio to make it all the way to Neon!), the staff order is all wrong. This is obvious from a) the fact that the syllables in the text box are ordered wrong and b) the colours of the staves don't follow the usual Neon colour order (pale orange, pale blue, green, yellow, navy, orange, pink). The neon green lines in the screenshot below indicate the staves which should be swapped to be ordered correctly:
<img width="479" alt="002r staff order wonkiness" src="https://user-images.githubusercontent.com/83373378/133279891-54b9fb96-d084-463e-a5e9-0e69a4cc302e.png">
This is the MEI of the file at the moment the screenshot was taken: 
[002r staff order wonkiness.mei.zip](https://github.com/DDMAL/Neon/files/7162925/002r.staff.order.wonkiness.mei.zip)

I tried the following fixes, all mentioned in the issue linked above, and none of them worked:
- Moving the staves around. The colour of the staff just changed as I moved it, eventually giving me another colour order that was also wrong:
https://user-images.githubusercontent.com/83373378/133282356-801bac60-a481-451e-b5d1-f6f2385061e5.mov
- Once I did manage to get the colour order correct, but only when the blue staff was too high. Moving it to the correct place made it revert to green:
https://user-images.githubusercontent.com/83373378/133282648-a25191c2-8579-4319-a9e0-57792403b245.mov
- Reassigning neumes to the correct staff. This drama happened:
https://user-images.githubusercontent.com/83373378/133282762-07597946-4755-4d49-a0e4-2ec1447d0cdd.mov
- Deleting an entire staff and putting it back in. No change.

The one thing that did work was deleting both swapped staves and putting them back in:
https://user-images.githubusercontent.com/83373378/133282862-1d783026-b561-4caf-9bc6-7e0c1a8de7b9.mov
Considering the number of wrong staves and the number of neumes per staff, I don't consider this option viable, because it means manually inputting the neumes on half the staves of the page.

**Comment by JoyfulGen** [comment] 2021-09-14 15:49
Update: I had time to run two more folios (012r and 099v) and both were fine, so it looks like this issue isn't too common.

**Comment by yinanazhou** [comment] 2021-09-20 19:51
Hi @JoyfulGen, is this what it is like when you first open Neon? If so, I guess this issue regards more how the input MEI file is generated by Rodan.

**Comment by JoyfulGen** [comment] 2021-09-21 17:23
> Hi @JoyfulGen, is this what it is like when you first open Neon? If so, I guess this issue regards more how the input MEI file is generated by Rodan.

Yes! The staves look like this when I open Neon and nothing I do seems to change it.

**Comment by JoyfulGen** [comment] 2021-12-07 18:58
Important update: It looks like the staff order issue is at least partly due to actions performed within Neon. I think it has something to do with the staves overlapping, but I'm having a lot of trouble reproducing the problem consistently. The following video is kind of long, but it illustrates all the issues clearly (the issues are explained below, in order of appearance):

https://drive.google.com/file/d/1VBN7f6x1w3oeVPeMa1rlY5O3e6UPdPGo/view?usp=sharing

- At the beginning, when I highlight the staves, they're all in the correct order (pale orange, pale blue, green, yellow, blue, orange, pink).
- If I move the first pale orange staff so that it slightly overlaps the pale blue one below it, Neon confuses their order and inverts them; the top staff is now pale blue. But when I move the top staff back, the colours revert to normal and all is well.
- Then if I move the second staff (pale blue) on top of the staff below it (green), it's the colours of the FIRST and second staff that are inverted. Again though, moving the staff back fixes everything.
- Then things get spicy: when I move the third staff (green) on top of the staff below it (yellow), the colours of those two staves switch. This time, they don't switch back, no matter what I do. I believe this is what results in the final staff order being wrong.
- Finally, when I go to another random staff lower in the page and I overlap it with the one below it, absolutely nothing happens. The colours don't move and the staff order remains correct.

So moving a staff so it overlaps slightly with the one below it has three distinct outcomes:
1. Nothing happens. This is fine.
2. The colours switch, but they switch back if the staves are put back in their correct place. This is also fine.
3. The colours switch permanently. This is not fine, because that means the staves are in the wrong order in the MEI and the lines of syllables are wrong as well. The only fix I've found is to delete both staves and put them back in, and in Einsiedeln this is no small job.

This is the MEI file of the folio in the video (Einsiedeln 004r):
[004r.mei.zip](https://github.com/DDMAL/Neon/files/7670856/004r.mei.zip)

I'm going to keep trying to find the reason behind the three possible outcomes and will update the issue if I figure it out. I'm also going to upgrade the priority to MEDIUM, because this has now happened in three folios (of 6).

**Comment by JoyfulGen** [comment] 2021-12-07 19:21
So... the plot thickens. Now the colours are changing even if the staves don't even touch. I was hopeful that I could at least avoid the issue happening by adjusting the staves without ever letting them overlap, but now I'm at a loss.

https://user-images.githubusercontent.com/83373378/145092415-80bbd3fc-9896-4a84-9dad-b9302c04aa55.mov

**Comment by yinanazhou** [comment] 2021-12-09 21:24
Hi @JRegimbal, could you please have a look at this issue? I thought it might relate to the position of `<sb>` or `custos`, but when I tested it, I cannot consistently reproduce the issue by changing their positions.

**Comment by JoyfulGen** [comment] 2021-12-15 16:45
**A summary:** 

@yinanazhou explained to me that the positioning of the staff is determined by the x and y coordinates of its upper-left corner. If two staves don't overlap, their order is determined by the y coordinate. However, if the staves DO overlap, their order is determined by the x coordinate. Therefore, two staves can be in the wrong order if the upper-left x coordinate of the top staff is to the right of the upper-left coordinate of the staff below it. 

SOLUTION: if the staff order is wrong, making the upper-left corner of the top staff further to the left than that of the bottom staff corrects the order. I've tried this several times and it's worked every time. 

ISSUE: The fix is completely viable, but the actual issue is still weird. In the video above, the staff order is wrong even if the staves aren't overlapping at all. Are the bounding boxes of the staves bigger than the staves themselves? Also, the one problem with extending the staff to correct the order is that the staff becomes much longer than the staff on the page.

Here's a video illustrating the fix: the yellow and green staves are switched (should be green first), but extending the top staff to the left makes them switch back.

https://user-images.githubusercontent.com/83373378/146228024-837c2d61-f6ed-4137-b37e-a89adc479ba3.mov

**Comment by annamorphism** [comment] 2021-12-15 18:07
@JoyfulGen I also found this solution independently! But it does make the staff "too long."
I too would like to know more about the bounding box of the staff. It does extend into the "ledger lines" above and below (e.g. the yellow neumes in line 2 in the example above)--do those affect the "intersection" of the staff areas?

**Comment by martha-thomae** [comment] 2021-12-15 18:31
@yinanazhou, seeing the details now, I think this should be fixed within Neon, and not by the user. Maybe change the heuristics a bit?

> However, if the staves DO overlap, their order is determined by the x coordinate. Therefore, two staves can be in the wrong order if the upper-left x coordinate of the top staff is to the right of the upper-left coordinate of the staff below it.

Maybe look at this comment by Juliette for another editor that seems to have a similar heuristic for determining the staff order and the solution she proposes: https://github.com/MeasuringPolyphony/mp_editor/issues/95#issuecomment-961890966

**Comment by martha-thomae** [comment] 2021-12-15 21:18
@yinanazhou, the proposed solution consists of evaluating both the intersection in `y` and `x`. Instead of assuming that if the systems intersect in `y`, they must be side-by-side (and the left-most system is ordered first); we can also evaluate if they intersect in `x`. If the intersection in `x` is significant (as would be in the example video shown above), and the intersection in `y` is not that significant (same example), then we can assume that the systems are one above the other (rather than side-by-side) and order them based on their `@uly` coordinate.

@JoyfulGen could you send two files to test this solution later? One file could be the one you just showed in the video, where one needs to enlarge the previous system due to an ornamental letter at the beginning of the system. The other file could be something that has two staves (two systems) at the same height (e.g., a staff cut by an ornamental letter in the middle).

Thank you!

**Comment by martha-thomae** [comment] 2021-12-15 21:27
@yinanazhou, last note for today: once this is corrected, you can remove the note in the [wiki](https://github.com/DDMAL/Neon/wiki/Instructions). Thank you!

**Comment by yinanazhou** [comment] 2021-12-18 20:54
Hi, I have already merged the changes in #736. I made the staff order only depend on the `x` coordinate if there is overlap on the `y` axis, and the `x` overlap is smaller than the half-length of the staff line. I will close this issue. If it needs further adjustment, please let me know!

**Closed by yinanazhou** 2021-12-18 20:54 UTC
Labels: bug, Severity: MEDIUM, Project: Neon
