### ISSUE TITLE
Custos missing in the last line of the folio page in Neon

### ISSUE THREAD

**Issue by carrieeex** [DDMAL/Neon#670] opened 2021-05-14 15:52 UTC
When we were correcting and reviewing the mei file in Neon within Rodan2, the last custos never shows up when we opened the MEI file we just corrected... so it's like: correcting MEI file in Neon - validate - download the corrected Neon MEI - open the MEI in Neon to review - custos dissapears

<img width="518" alt="屏幕截图 2021-05-14 155703" src="https://user-images.githubusercontent.com/59303880/118280066-6d194e80-b4fe-11eb-80a8-b86830f886c4.png">

**Comment by martha-thomae** [comment] 2021-05-17 18:57
Are you saying that the custos was there before? So, you saw the custos and click on "validate", and when you open the same file for the second time in Neon, the custos disappeared?

If this is the case, could you save the MEI file before clicking on validate (the first time) and verify that the custos is encoded within that MEI file? thank you!

**Comment by carrieeex** [comment] 2021-05-18 07:52
> Are you saying that the custos was there before? So, you saw the custos and click on "validate", and when you open the same file for the second time in Neon, the custos disappeared?

Yes that's what we encountered!

> If this is the case, could you save the MEI file before clicking on validate (the first time) and verify that the custos is encoded within that MEI file? thank you!

ok! So I checked the MEI files: after reviewing and adding everything, the custos is indeed encoded in the MEI file before I validate. And it was still there after I validated it (so the MEI files are the same before validation and in the resources page of that workflow run); while after I imported the same file back to Neon workflow to review, the last custos disappeared:

022r custos added, before validation:
<img width="970" alt="missing custos - 022r custos added" src="https://user-images.githubusercontent.com/59303880/118611456-713fb780-b7ef-11eb-83a8-df7a97d5917c.png">
and the MEI (before validation)
<img width="719" alt="missing custos - 022r custos added, before validation" src="https://user-images.githubusercontent.com/59303880/118612359-45710180-b7f0-11eb-8a76-e66a23aa74ca.png">
the MEI after validation:
<img width="689" alt="missing custos - 022r custos added, after validation" src="https://user-images.githubusercontent.com/59303880/118612366-473ac500-b7f0-11eb-88e1-2eff06201795.png">

and then put it back to the Neon workflow to review, the last custos dissappeared:
<img width="957" alt="missing custos - 022r imported back to neon" src="https://user-images.githubusercontent.com/59303880/118612384-4c980f80-b7f0-11eb-86ce-ca6ad283b9ab.png">
the MEI:
<img width="692" alt="missing custos - 022r back to neon" src="https://user-images.githubusercontent.com/59303880/118612385-4d30a600-b7f0-11eb-931c-2567e2ed2c25.png">

**Comment by martha-thomae** [comment] 2021-05-19 16:22
Thanks, @carrieeex! the screenshots of the MEI file helped a lot, specially in discovering that this might be the same issue as in #673.

**To the developers:** the issue seems to be that the last element within the `<layer>` element disappears when the file is re-uploaded into Neon. In this case, the last element within the layer is the `<custos>`. In the case of #673, the last element within the layer is a `<syllable>` element. (Please refer to [this comment](https://github.com/DDMAL/Neon/issues/673#issuecomment-844258221).)

**Comment by JoyfulGen** [comment] 2022-05-27 15:48
This is a duplicate of https://github.com/DDMAL/Neon/issues/673. Closing it now.

**Closed by JoyfulGen** 2022-05-27 15:48 UTC
Labels: bug, Severity: LOW, Project: Neon, good first issue
