### ISSUE TITLE
Check if there are any out-of-bounds glyphs

### ISSUE THREAD

**Issue by jinh0** [DDMAL/Neon#920] opened 2022-07-12 13:40 UTC
And allow the user to remove them

**Comment by JoyfulGen** [comment] 2022-07-19 15:25
This looks good! I tried dragging various glyphs off the page and they jump right back. Very entertaining. There appears to be a small problems with bounding boxes though; I can't move them at all without getting an "Out of bounds" notification, as if the allowed bounds in this case is only where the bounding box currently is. I've just realized the same is true of staves.

As for notifications, from what I understand there are now three colours: blue for instructions, green for successful operations, and red for failed operations. I'm wondering if maybe instructions and successes could both be blue as they used to be, and failures could stay red. That would allow the failed operations to really stand out. I feel like three colours is a bit of an information overload, but I realize that might just be because I was so used to the blue. @annamorphism I'd love to know what you think!

**Comment by annamorphism** [comment] 2022-07-19 15:53
@JoyfulGen there's also orange for warnings!
I like the different colours--it means I don't actually have to READ all the words to know whether it's telling me to do something, or talking about something I already did. I do find the darker blue just a little hard to read? 
Also, splitting hairs here, why is "Click The Beginning Of The Second Neume" with capitals, but "Neume splitting successful" isn't? (I prefer the latter, myself.)

**Comment by annamorphism** [comment] 2022-07-19 15:54
@JoyfulGen wait we cross-commented. is your yellow my orange or is there a whole rainbow of colours?

**Comment by annamorphism** [comment] 2022-07-19 15:58
and while we're on the topic of error messages:
We get a single error message for glyph(s) out of bounds, but multiple error messages for syllables without neumes, which is a little overwhelming. If we only got one for each type of error, that would be better.

**Comment by annamorphism** [comment] 2022-07-19 16:01
also, on this folio (Einsie 26r) I get a warning that there are out of bounds glyphs:

![image](https://user-images.githubusercontent.com/67451875/179796198-337ccac7-084b-4893-81c6-590d5a705ce8.png)

but then when I use the action to remove them, they aren't there: 
![image](https://user-images.githubusercontent.com/67451875/179796412-3bab61a3-3ad8-4d10-9461-1922325cdc04.png)

and the MEI stays invalid.

**Comment by yinanazhou** [comment] 2022-07-20 04:15
> also, on this folio (Einsie 26r) I get a warning that there are out of bounds glyphs:
> 
> ![image](https://user-images.githubusercontent.com/67451875/179796198-337ccac7-084b-4893-81c6-590d5a705ce8.png)
> 
> but then when I use the action to remove them, they aren't there: ![image](https://user-images.githubusercontent.com/67451875/179796412-3bab61a3-3ad8-4d10-9461-1922325cdc04.png)
> 
> and the MEI stays invalid.

Hi @annamorphism, could you please provide the folio you are using? What is the element type for this OOB element?

**Comment by JoyfulGen** [comment] 2022-07-20 12:43
> @JoyfulGen wait we cross-commented. is your yellow my orange or is there a whole rainbow of colours?

Yes, my yellow is your orange, so I think four colours is what we got. And if you like 'em, I like 'em too! And I agree with only capitalizing the first word in the notifications.

**Comment by annamorphism** [comment] 2022-07-20 13:55
Ah, I figured it out--it's a bounding box, which can actually be dragged in without needing the MEI action.  However, it's confusing to be told there is a glyph that needs dealing with, and then also get a message that it isn't there. So either bounding boxes should also be affected by the MEI remove-OOB action, OR the warning needs to be different (or not exist) if the invalid MEI is caused by something you could take out, like a staff. 
(In this case there is also an accidental complicating matters--I'm not sure why these make folios invalid so often, and wonder if they also need a warning.)

**Comment by jinh0** [comment] 2022-07-20 17:33
Hey everyone, I have fixed the bounding box issue, but regarding staves, it's because clefs are really weird!

Clefs have a bounding box that starts from x=0 and y=29250??????
```
<use xlink:href="#E906" x="0" y="29250" height="223px" width="223px"></use>
```

Anyway, the fix I'm thinking of thus is that we exclude the bounding boxes of clefs in our OOB calculation.

But can somebody confirm whether clefs are supposed to have such weird coordinates?

**Comment by yinanazhou** [comment] 2022-07-20 17:35
Clefs shouldn't have these weird coordinates. Could you please check in verovio? I think it's the issue with two coordinate systems.

**Comment by yinanazhou** [comment] 2022-07-21 20:36
After discussing with @jinh0, the ghost clef is drawn in `DrawStaffDef()` in verovio. This function draws the clef in the staff definition, such as the clef at the beginning of the staff in the modern notation. In the neume notation, we draw the clefs separately. Therefore, we disabled the `DrawStaffDef()` in `DrawStaff()`.

**Comment by JoyfulGen** [comment] 2022-07-22 12:31
@yinanazhou I can move the top staff now! However, I can still resize a staff to stretch beyond the page edge and Neon doesn't seem to mind. I think it'd be best if that wasn't possible either.

**Comment by jinh0** [comment] 2022-07-22 13:11
- [ ] Resizing staff
- [ ] Resizing bounding boxes

**Comment by JoyfulGen** [comment] 2022-08-02 12:59
@jinh0 there's a slightly weird thing going on with bounding boxes. If I resize a bounding box, it becomes "passively" selected like the staves used to be. If I click on it nothing happens, I can't resize it again. All I can do is click elsewhere to deselect it, and then select it again. Here's a demo:

https://user-images.githubusercontent.com/83373378/182379866-c72c14f7-0c58-4033-98be-7f09b98e7b63.mov

**Comment by JoyfulGen** [comment] 2022-09-20 11:38
> @jinh0 there's a slightly weird thing going on with bounding boxes. If I resize a bounding box, it becomes "passively" selected like the staves used to be. If I click on it nothing happens, I can't resize it again. All I can do is click elsewhere to deselect it, and then select it again. Here's a demo:
> Weird.bounding.box.selection.mov

This is not a thing anymore! Closing this issue now, I think everything is resolved.

**Closed by JoyfulGen** 2022-09-20 11:38 UTC
