### ISSUE TITLE
bug: divLines do not get highlighted correctly

### ISSUE THREAD

**Issue by jinh0** [DDMAL/Neon#940] opened 2022-07-28 16:49 UTC
- [x] Divlines are not highlighted red when a staff is selected. This is inconsistent with when a divine is highlighted red when a syllable is selected.
- [x] Divlines have never shown their true colors when layerElement highlight option is turned on.

**Comment by yinanazhou** [comment] 2023-01-29 21:06
Hi @JoyfulGen, I've pushed the changes for this issue. Could you please check it? Thanks!

**Comment by JoyfulGen** [comment] 2023-02-07 12:06
@yinanazhou I can confirm that divLines now show the colour of their staff, are highlighted when the staff is selected, and show their colour when highlighting by layer element. Closing issue now!

**Comment by JoyfulGen** [comment] 2023-02-07 15:11
So sorry, small amendment to that. All the highlighting works just fine, but the divLines now sometimes become very small when in Neume or Syllable highlight.

Here's a demo, where I'm in Syllable highlight: if I do any action at all, the divLines immediately become all slender. If I go to either the Staff or Layer Element highlight, they become normal sized again. 

https://user-images.githubusercontent.com/83373378/217283365-8e135320-cb95-422a-ad51-a4e083afa12d.mov

This doesn't change any of their functions, but it does make them a bit harder to a) see and b) grab. I think it would be easiest for the user if they always stay the bigger size, regardless of wheter they're highlighted or not.

**Comment by JoyfulGen** [comment] 2023-02-08 14:07
Found two more little quirks:

1. When a staff is selected, the whole thing is highlighted in red, including the divLines. However, if you resize the staff, the divLines stop being highlighted. Demo:

https://user-images.githubusercontent.com/83373378/217551291-0ec36ae8-1a4d-4137-bf92-8ec35e29da8b.mov

2. When highlighting by Staff or Layer Element, the divLines initially have colour, as they should. However, if you click on the Syllable selector and then on any other selector, the divLines become black again. This doesn't happen if you click only on the Neume selector, for example--you have to click on Syllable selector first. To be very clear, this is the sequence of events:
a) Highlight by Staff or Layer Element (divLines are colourful);
b) Click on Syllable selector tool;
c) Click on any other selector tool --> divLines become black
d) Make any change --> divLines get their colour back.

https://user-images.githubusercontent.com/83373378/217552126-f7ce8910-2c87-4bb6-bcde-af483b22a644.mov

Once again, these quirks don't actually hinder correction, but they also don't correspond to the ideal divLine behaviour.

**Comment by yinanazhou** [comment] 2023-03-17 02:58
Hi @JoyfulGen, the quirks you mentioned above should be fixed in the latest merge. Please let me know if it works well. Thanks!

**Comment by JoyfulGen** [comment] 2023-03-17 09:40
All three quirks fixed! Thank you very much. Closing issue now.

**Comment by JoyfulGen** [comment] 2023-03-22 13:53
Very sorry to keep flip-flopping, but something else has popped up.

It used to be that when in Syllable highlight, divLines that were part of a syllable were the same colour as the neumes in that syllable, rather than black like all other divLines. This feature is very useful, because it allows the user to quickly tell if a divLine has been inserted to a syllable or not. However, since the most recent fixes, divLines are always black in the syllable highlight, whether they're part of a syllable or not. I would love to have the feature back!

Also, small detail: when selecting a syllable that contains a divLine, that divLine becomes highlighted in red like the neumes around it, which makes sense. However, if I click elsewhere to unselect that syllable, the divLine stays highlighted. Here's a demo:

https://user-images.githubusercontent.com/83373378/226925693-dbdef0db-990c-4dee-94ad-0954024a5b27.mov

**Comment by yinanazhou** [comment] 2023-04-19 14:45
Hi @JoyfulGen, I've pushed the changes for this issue

**Comment by JoyfulGen** [comment] 2023-04-20 10:28
Fixed, thank you! Closing issue now.

**Closed by JoyfulGen** 2023-04-20 10:28 UTC
