### ISSUE TITLE
All divisios disappear when the UNDO button is clicked

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#730] opened 2021-11-22 14:21 UTC
Exhibit A:

There are divisios in the three first staves, and when I click the UNDO button they all disappear. This happens no matter how many divisios I've input, or if I did other actions between adding divisios. 

https://user-images.githubusercontent.com/83373378/142877193-7eeca389-4bbf-437d-94ca-78d7ec4e19c9.mov

(The INVALID status is another issue that I'm currently trying to figure out.)

**Comment by JoyfulGen** [comment] 2021-11-22 14:59
I've found another disappearing divisio issue, I don't know if it's related or not:

Divisios that are in the MEI file right out of the e2e workflow (so that have been identified by the IC) appear in Neon browser when I upload the file. However, if I reupload a file that I manually input divisios in, the divisios don't appear. They're definitely still in the MEI file, but they don't show up on Neon.

There is a small difference between the MEI files for divisios that the IC found and divisios I added manually. Here's a DivLine that the IC found and encoded (this one shows up on Neon):
`<divLine xml:id="m-7e46c3c1-b123-4a68-85e9-3cd33a9c2cdf" form="maxima" facs="#m-2192dd5e-2826-4ca3-91c1-1ecb086f96e7" />`

And here's a DivLine that I added myself on Neon (this one doesn't show up on Neon):
`<divline xml:id="dline-0000000891833664" facs="#zone-0000001593540864" form="maxima"/>`

From what I can tell, the `facs` and the `form` are switched. There also appears to be an extra space before the / at the end of the first one, for some reason.

**Comment by yinanazhou** [comment] 2021-11-24 15:15
Hi @JoyfulGen , I have pushed some changes yesterday. I cannot reproduce the disappearing division issue right now on browser neon. Could you please test again whether these two issues still happen? Thank you!

**Comment by JoyfulGen** [comment] 2021-11-29 13:45
> Hi @JoyfulGen , I have pushed some changes yesterday. I cannot reproduce the disappearing division issue right now on browser neon. Could you please test again whether these two issues still happen? Thank you!

I am delighted to report that they don't! Divisios don't disappear when I click the UNDO button, and they also don't disappear when I reupload the file to browser Neon. Thank you!

**Comment by yinanazhou** [comment] 2021-11-29 18:34
Glad to know! In this case, I will close this issue.

**Closed by yinanazhou** 2021-11-29 18:34 UTC
Labels: bug, Severity: MEDIUM, Project: Neon
