### ISSUE TITLE
certain syllables not ungrouping

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#647] opened 2021-01-23 01:04 UTC
Certain syllables at the ends of lines don't allow ungrouping or merging, for example: the final syllables of lines 1-3 of folio 1r.
On folio 33r, the final syllables of lines 2, 4, 6, and 9 don't allow it, but those of all other lines on the page do (cf the attached screenshots.) 
![image](https://user-images.githubusercontent.com/67451875/105563399-eab91480-5ceb-11eb-8353-e41c3a20d159.png)
![image](https://user-images.githubusercontent.com/67451875/105563438-0ae8d380-5cec-11eb-8145-d41d4384a96d.png)

**Comment by annamorphism** [comment] 2021-01-23 01:24
This seems to have been an issue related to my edit history in some way--it happens on my uploaded .json file of the manuscript,  and seemed also to be happening on the sample document, but when I reverted the document it stopped happening.

**Comment by annamorphism** [comment] 2021-01-25 20:52
Actually, still a problem--here's folio 001r, line 3, on a fresh sample document.
![image](https://user-images.githubusercontent.com/67451875/105764607-2db1fc80-5f25-11eb-8fa0-1b5c994566fe.png)

**Comment by annamorphism** [comment] 2021-01-25 23:13
More information about this issue: the problem arises when a linked syllable has the component(s) or neume(s) on the other line deleted. The resulting syllable (which is no longer linked) lacks the ability to ungroup, merge, or delete. (The constituent neumes can be deleted, however.)

**Comment by JRegimbal** [comment] 2021-01-26 16:28
Issue appears to be previously linked syllables refer to a now deleted syllable.

**Comment by JoyfulGen** [comment] 2022-02-07 13:36
This issue is a duplicate of https://github.com/DDMAL/Neon/issues/675, which has been successfully fixed and closed. Closing it now.

**Closed by JoyfulGen** 2022-02-07 13:36 UTC
