### ISSUE TITLE
odd behaviour when re-grouping neumes

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#657] opened 2021-03-09 23:20 UTC
94v, line 11, has a long neume (linked to the next line), which should be regrouped into several smaller neumes. 
![image](https://user-images.githubusercontent.com/67451875/110550279-5d961780-8101-11eb-867d-37822dc2afbe.png)
However, the resultant neumes appear in a strange colour order in the syllable:
![image](https://user-images.githubusercontent.com/67451875/110550867-781cc080-8102-11eb-8d9b-c69faacf6181.png)
"Grouping" the neumes solves this issue (which is mostly aesthetic), but it is not obvious why one should have to re-group neumes that were already grouped in the first place. 
![image](https://user-images.githubusercontent.com/67451875/110550932-95ea2580-8102-11eb-97bf-8c8dc32803c6.png)

**Comment by annamorphism** [comment] 2021-06-07 21:45
This seems to be partially related to https://github.com/DDMAL/Neon/issues/680
Part of the issue is that newly grouped neume components are always appended to the end of the syllable, no matter what order they are in on the page; this can create very strange orderings, especially if some singletons are involved (because they stay in their former spots). Regrouping the whole neume fixes it by putting them back in page order, but it is far from obviosu to the user that they need to do so. 
Solutions : 1) Not attach the newly grouped components at the end, but retain their ordering or 2) if they must be put at the end of the syllable, indicating to the user somehow that they should group the neumes.

**Comment by annamorphism** [comment] 2021-06-17 23:39
The problem of grouping and re-grouping also happens at the neume component level.For example, in the following picture, the blue neume on "ce" has not been grouped with the others properly, and the neume displays as if F3 is appended to the end:
 ![image](https://user-images.githubusercontent.com/67451875/122484657-08409080-cfa3-11eb-879c-f4fa63a628c6.png)
￼￼￼
Grouping the neume *components* puts things in a strange order (with E counted twice?)
![image](https://user-images.githubusercontent.com/67451875/122484824-771de980-cfa3-11eb-9005-ded3383a8a1b.png)

Grouping again:
![image](https://user-images.githubusercontent.com/67451875/122484831-800ebb00-cfa3-11eb-9d1a-4a197abcfe41.png)

And finally, grouping neume components into the correct order: 
![image](https://user-images.githubusercontent.com/67451875/122484843-8b61e680-cfa3-11eb-875f-fa5887409c7b.png)

**Comment by JoyfulGen** [comment] 2022-02-03 16:48
This appears to be a duplicate of https://github.com/DDMAL/Neon/issues/722. Since that issue was fixed and closed, I'll close this one as well.

**Closed by JoyfulGen** 2022-02-03 16:48 UTC
Labels: bug, duplicate
