### ISSUE TITLE
staff split/merge options

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#699] opened 2021-07-13 18:40 UTC
The option to split or merge a staff only appears if you click on elements (i.e. neumes) ON the staff in question. Since a split is likely to be needed where there are no elements, this is confusing...

**Comment by yinanazhou** [comment] 2021-12-31 19:38
The issue is solved in the latest merge. Clicking anywhere on the staff will have the option to split or delete a staff. The merge option only appears when more than one staves are selected. I will close this issue.

**Closed by yinanazhou** 2021-12-31 19:38 UTC
