### ISSUE TITLE
Accidentals only appear on top line of staff in browser Neon and refuse to be moved elsewhere

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#720] opened 2021-09-28 12:23 UTC
When inputting an accidental (it happens for both flats and naturals), the symbol appears on the top line of the staff, regardless of where I clicked. If I try to select it and drag it to the correct place, it just hops right back to where it was before. Video evidence with 080v of the Salzinnes manuscript:

https://user-images.githubusercontent.com/83373378/135085633-f2c5ed09-bc11-4183-a1f5-c3ff3f817720.mov

**Comment by yinanazhou** [comment] 2021-12-29 17:03
As pointed out by @JRegimbal, the issue is caused by the confusion of the drawing and logical coordinate systems in verovio. In the drawing system, the `y` axis starts with `0` at the **top** and increases moving down. The logical system starts with `0` at the **bottom** and increases moving up. In `view_element.ts`, function `DrawAccid` and `DrawDivLine` mixed up the two systems for `uly`, thus making `uly` extremely large, which also caused issue #738. The issue is solved in merge #739. I will thus close this issue.

**Closed by yinanazhou** 2021-12-29 17:03 UTC
Labels: bug, Severity: MEDIUM, Project: Neon
