### ISSUE TITLE
Occasionally, browser Neon will display MEI status as unknown with a blank page

### ISSUE THREAD

**Issue by thesoundbyle** [DDMAL/Neon#688] opened 2021-06-18 15:05 UTC
Currently, browser neon will sometimes have trouble displaying certain folios and show an MEI status of "unknown"

Issue has been experienced in Salzinnes folios: 001r (Chrome) and 174r (Firefox)

Reuploading the folio has seen success as a workaround. 

![Screenshot_1](https://user-images.githubusercontent.com/62864127/122581509-1df69a00-d025-11eb-8571-cd7b8c26c574.jpg)
[CDN-Hsmu_M2149.L4_001r.txt](https://github.com/DDMAL/Neon/files/6695899/CDN-Hsmu_M2149.L4_001r.txt)
[Neon - Corrected 174r.txt](https://github.com/DDMAL/Neon/files/6696132/Neon.-.Corrected.174r.txt)

**Comment by kemalkongar** [comment] 2021-06-22 15:14
Are the pages mentioned part of the default Salzinnes manuscript or custom uploads? If custom, could you send the MEI files for them? If not, the issue is not replicable and will be closed.

**Comment by martha-thomae** [comment] 2021-06-22 15:26
These are definitely uploads.

@thesoundbyle, could you provide these MEI files?
Please, always include the MEI files with the issue so that the devs are able to replicate it (they do have the images from the shared folder, but not the MEI files used).

**Comment by kemalkongar** [comment] 2021-06-22 15:28
We talked over Slack, apparently this happens with the default files. @thesoundbyle will be closing the issue sometime next week if it doesn't pop up, since we can't replicate it.

**Comment by martha-thomae** [comment] 2021-06-22 15:31
Ok, please try to keep your discussions in the GitHub issues themselves. That helps for keeping a paper trail. 

Thanks for summarizing the feedback here, @kemalkongar.

**Comment by martha-thomae** [comment] 2021-06-22 15:45
@thesoundbyle, are you sure that it was with the default Salzinnes pages?
>Issue has been experienced in Salzinnes folios: 001r (Chrome) and 174r (Firefox)

Right now that I am in browser Neon, if I select a sample document (the default document) and a page in it—as in the two following screenshots—I cannot select pages 001r and 174r. They are just not an option.

![Screen Shot 2021-06-22 at 11 41 39 AM](https://user-images.githubusercontent.com/13948831/122956356-ec484080-d34e-11eb-8950-ba60df6c57ef.png)

![Screen Shot 2021-06-22 at 11 41 46 AM](https://user-images.githubusercontent.com/13948831/122956363-ee120400-d34e-11eb-8b2d-e4cebba5d6cc.png)

![Screen Shot 2021-06-22 at 11 42 19 AM](https://user-images.githubusercontent.com/13948831/122956371-f0745e00-d34e-11eb-93f7-339b5031b21e.png)
The options go from CF-005 to CF-056.

Am I missing something? I thought you uploaded both the image and the MEI file since you were working on correcting (double-checking) the folios processed by the other testers.

**Comment by thesoundbyle** [comment] 2021-06-22 15:51
Forgive me if i’m mistaken but it seems that user loaded pages/manuscripts are cached locally. That might be why you can’t see mine or @carrieeex uploads

**Comment by martha-thomae** [comment] 2021-06-22 15:57
@thesoundbyle: So, you did upload them. They are not the default images (the ones that browser Neon has by default).
Could you then submit here the MEI files you used when uploading the images?

(If I am missing something that you discussed, @kemalkongar and @thesoundbyle, just let me know.)

**Comment by martha-thomae** [comment] 2021-06-22 15:59
>Are the pages mentioned part of the default Salzinnes manuscript or custom uploads?

I think there might have been a small miss-understanding because the default images of browser Neon and the images we are processing are both from the Salzinnes manuscript. The difference is that the ones that are in browser Neon by default are old images (they have a white background and color patch at the bottom, and they have their own issues). We are processing new images (the ones with the black background and color patch at one side).

**Comment by thesoundbyle** [comment] 2021-06-22 16:21
> > Are the pages mentioned part of the default Salzinnes manuscript or custom uploads?
> 
> I think there might have been a small miss-understanding at the beginning of the discussion, because the default images of browser Neon and the images we are processing are both from the Salzinnes manuscript. The difference is that the ones that are in browser Neon by default are old images (they have a white background and color patch at the bottom, and they have their own issues). We are processing a new set of images from Salzinnes (the ones with the black background and color patch at one side).

Ahh I can see how that can be confusing. Yes, we are all working currently on the Salzinnes manuscript. but the folios in question are user uploaded. 
The requested MEI files have been added to the issue. 
As stated in the issue, the files are valid when reuploaded.

**Comment by martha-thomae** [comment] 2021-06-22 16:23
Thank you! :)

**Closed** 2022-04-26 12:30 UTC
Labels: bug, Project: Neon
