### ISSUE TITLE
invalid page, invisible custos? - Neon allows user to input glyphs outside of facsimile, results in invalid folio

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#700] opened 2021-08-10 20:40 UTC
In an issue possibly related to #651 and #697, a page turned up as invalid after some very trivial button click (sadly, I don't remember what). "Undo" created an apparently identical but valid page (see below)
![image](https://user-images.githubusercontent.com/67451875/128930764-a27b2bdf-b6cd-407b-85da-fb3101fb0466.png)
![image](https://user-images.githubusercontent.com/67451875/128930836-efe5f545-b0bf-4807-b748-14550f2d782d.png)
As it turns out,  the MEI files for these two states is not identical; the "invalid" version has a custos on G at the end of the tenth staff,  where the "valid" one does not:
![image](https://user-images.githubusercontent.com/67451875/128931240-74514277-d1fd-4474-ade2-d1d746bd40bf.png)
![image](https://user-images.githubusercontent.com/67451875/128931368-2eddf893-5775-441f-9c3f-84b041292012.png)

The zone for this otherwise invisible custos is outside the bounds of the page: 
![image](https://user-images.githubusercontent.com/67451875/128931611-42bc2c79-6ce2-4cda-90a3-88345230bd8e.png)

**Comment by annamorphism** [comment] 2021-08-10 20:47
aha! The problem seems to be that one might click outside of the facsimile while still in "insert" mode. On the right side of the page this amounts to clicking in the area with the edit information and does nothing. In the white space below the page, the elements are inserted at the same x coordinate and a y-coordinate corresponding to C0 on whatever the lowest staff is. However, clicking in the white space either to the left or above the facsimile "inserts" the element into a zone with negative (i.e. invalid) coordinates.

**Comment by JoyfulGen** [comment] 2022-02-03 16:25
Whoa, I think this explains a few invalid folios I had that I couldn't figure out... I just experimented with it and I got the same results. You can tell a glyph is being added, because the other glyphs change colour (see below for pretty video). This is a cool discovery! The problem is that once the glyph is input into the white space around the facsimile, it's not visible in any way, so you can't select it and delete it. If you realize the problem fast enough, you can undo the actions and everything is fine. If you don't, the only way to remove the glyph is by going in the MEI, as @annamorphism did.
I think a good fix would be to restrict the possible glyph-inputting area to the facsimile, so that even if you do click on the white space by mistake, nothing happens.

https://user-images.githubusercontent.com/83373378/152384270-7777a992-afbb-4f31-b706-10c3ea8a8fbd.mov

**Comment by yinanazhou** [comment] 2022-07-14 13:11
Hi @JoyfulGen, I've pushed the changes for this issue to the Github page. Please let us know if it works as expected.

**Comment by yinanazhou** [comment] 2022-07-20 04:12
@jinh0 noticed that the OOB check has two issues with bounding box:

- [ ] Moving any bbox to anywhere would show the OOB error (traced back to `selectionBBox`, will discuss tomorrow)
- [ ] resizing bbox to OOB has no OOB check

**Comment by yinanazhou** [comment] 2022-07-20 04:13
> @yinanazhou this is great! I love the error message, everything is very clear. I tried inserting all the single glyphs and everything works. However, Neon did allow me to insert a staff out of bounds, which made the folio invalid. Could you extend the fix to include staves?

Hi @JoyfulGen, I have pushed the changes for staff insertion. Please let us know if it's working as expected. Thanks!

**Comment by annamorphism** [comment] 2022-07-20 13:59
> Also, in the case of BBoxes I can neither resize them or move them, whereas I can't move the first staff, but I can resize it.

I can resize them but not move them! I can even resize them so an edge goes off the page, but then not move it so it's all on the page. Wild!

**Comment by jinh0** [comment] 2022-07-20 17:37
Hey everyone, I have fixed the bounding box issue (I'll push the changes soon), but regarding staves, it's because clefs are really weird!

Clefs have a bounding box that starts from x=0 and y=29250??????

<use xlink:href="#E906" x="0" y="29250" height="223px" width="223px"></use>
Anyway, the fix I'm thinking of thus is that we exclude the bounding boxes of clefs in our OOB calculation.

But can somebody confirm whether clefs are supposed to have such weird coordinates?

**Comment by JoyfulGen** [comment] 2022-07-21 15:01
@jinh0 it looks like liquescents are also behaving weirdly. I can't move either upwards or downwards liquescents without getting an OOB notification.

**Comment by annamorphism** [comment] 2022-07-21 15:15
@JoyfulGen I can move some of the liquescents, some of the time...as long as I'm very gentle and stay on the staff and don't move left or right. But if I move them too many times or in the wrong way they get very upset and don't want to do anything anymore.

**Comment by yinanazhou** [comment] 2022-08-08 13:29
Hi @JoyfulGen, I've pushed the fix for the bbox and staff resizing.

**Comment by JoyfulGen** [comment] 2022-08-08 13:33
Indeed! Neon won't let me resize a bbox or a staff outside the page anymore. This is fixed!

**Comment by JoyfulGen** [comment] 2022-09-20 11:46
From what I understand, all of these issues have been fixed. Neon won't let you input, drag, or resize anything out of the page's bounds. Closing issue now.

**Closed by JoyfulGen** 2022-09-20 11:46 UTC
Labels: Severity: MEDIUM, Project: Neon
