### ISSUE TITLE
inserted neumes lead to misplaced syllables

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#634] opened 2020-06-26 05:31 UTC
On 1r, line 3,  all inserted neumes have their corresponding <> inserted between <u> and <ae>. A similar issue happens on line 4, and the first half of line 5, but other inserted neumes on the page have the <> correctly inserted between those of the neumes to either side.
(version 719e315)

**Comment by JRegimbal** [comment] 2020-06-29 12:23
Hi @annamorphism. I'm having a bit of trouble understand the issue. What's the "<>" referring to here?

**Comment by JRegimbal** [comment] 2020-06-30 18:20
Clarification and update: This issue occurs in the sorting function in Verovio and is caused by the presence of syllables without neumes, which cause issues in the sorting function since we do not want them to determine order before the neumes themselves. When syllables without neumes are removed, this error no longer occurs.

Actions to take (any of these should prevent this issue from blocking a workflow):
* [ ] Allow syllables without neumes to be deleted in Neon (these cannot be added normally).
* [ ] Sort by `syl` location if no neumes are present in the syllable. (note: must be done in Verovio)
* [ ] Remove `syllable` elements without any `neume` from imported MEI files since they cannot be meaningfully edited.

**Comment by JRegimbal** [comment] 2020-06-30 19:24
Closing since I can no longer cause the problem. @annamorphism if this happens again let me know and I'll reopen the issue.

**Closed by JRegimbal** 2020-06-30 19:24 UTC
Labels: Project: Neon, Severity: MEDIUM, bug
